In [51]:
import pandas as pd
import numpy as np

In [52]:
df= pd.read_csv("/content/questionAnswer.csv")

In [53]:
df.head()

                                          question      answer
0                   What is the capital of France?       Paris
1                  What is the capital of Germany?      Berlin
2               Who wrote 'To Kill a Mockingbird'?  Harper-Lee
3  What is the largest planet in our solar system?     Jupiter
4   What is the boiling point of water in Celsius?         100

In [54]:
# tokenize
def tokenize(text: str)-> list:
  text= text.replace('?' ,"")
  text= text.replace("'", "")
  return text.lower().split(" ")

In [55]:
tokenize("What is the capital of France?")

['what', 'is', 'the', 'capital', 'of', 'france']

In [56]:
# makes a dictionary of vocabulary
vocab= {'<UNK>': 0}   #unk means undefined/unknown here
i=1

In [57]:
for row in df.values:
  question, answer= row
  tokenized_question= tokenize(question)
  tokenized_answer= tokenize(answer)
  tokens= tokenized_question + tokenized_answer
  for token in tokens:
    if token not in vocab:
      vocab[token]= i
      i= i+1

In [58]:
len(vocab)

324

In [59]:
# convert word into numerical indices
def to_indices(text):
  indices= []

  for token in tokenize(text):
    if token in vocab:
      indices.append(vocab.get(token, ""))

    else:
      indices.append(vocab.get( "<UNK>"))

  return indices

In [60]:
to_indices(df.iloc[0, 0])

[1, 2, 3, 4, 5, 6]

In [61]:
df['question']= df['question'].apply(to_indices)
df['answer']= df['answer'].apply(to_indices)

In [62]:
df.sample(10)

                                   question answer
61              [1, 87, 229, 230, 231, 232]  [233]
51         [1, 2, 3, 146, 86, 19, 192, 193]  [194]
64                    [10, 96, 3, 104, 239]  [240]
81           [78, 79, 288, 81, 19, 14, 289]   [85]
73          [42, 137, 2, 138, 39, 175, 269]   [99]
18             [78, 79, 80, 81, 82, 83, 84]   [85]
82  [42, 290, 291, 118, 292, 158, 293, 294]  [295]
19             [42, 86, 87, 88, 89, 39, 90]   [91]
59         [1, 2, 3, 221, 5, 222, 223, 224]  [225]
89        [42, 137, 2, 62, 39, 3, 322, 323]    [6]

In [63]:
df.values.ndim

2

In [64]:
df.iloc[1].values

array([list([1, 2, 3, 4, 5, 8]), list([9])], dtype=object)

In [65]:
import torch
import torch.optim as optim
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

In [66]:
class CustomDataset(Dataset):
  def __init__(self, df):
    self.df= df


  def __len__(self):
    return df.shape[0]



  def __getitem__(self, index):
    return torch.tensor(self.df.iloc[index]['question']),torch.tensor(self.df.iloc[index]['answer'][0])

In [67]:
dataset= CustomDataset(df)

In [68]:
len(dataset)

90

In [69]:
dataloader= DataLoader(dataset, pin_memory= True, shuffle= True, batch_size= 1)

In [70]:
for x, y in dataloader:
  print(x, y)
  print("-"*50)

tensor([[ 42, 137,   2, 226,  12,   3, 227, 228]]) tensor([155])
--------------------------------------------------
tensor([[ 42, 137,   2,  62,  39,   3, 322, 323]]) tensor([6])
--------------------------------------------------
tensor([[ 42, 216, 118, 217, 218,  19,  14, 219,  43]]) tensor([220])
--------------------------------------------------
tensor([[1, 2, 3, 4, 5, 8]]) tensor([9])
--------------------------------------------------
tensor([[ 10,  96,   3, 104, 239]]) tensor([240])
--------------------------------------------------
tensor([[ 42, 200,   2,  14, 201, 202, 203, 204]]) tensor([205])
--------------------------------------------------
tensor([[ 42, 318,   2,  62,  63,   3, 319,   5, 320]]) tensor([321])
--------------------------------------------------
tensor([[  1,   2,   3, 180, 181, 182, 183]]) tensor([184])
--------------------------------------------------
tensor([[ 42, 250, 251, 118, 252, 253]]) tensor([254])
--------------------------------------------------
tensor([[  1,   2,   3,  37,  38,  39, 161]]) tensor([162])
--------------------------------------------------
tensor([[ 42, 137,   2, 138,  39, 139]]) tensor([53])
--------------------------------------------------
tensor([[ 1,  2,  3, 59, 25,  5, 26, 19, 60]]) tensor([61])
--------------------------------------------------
tensor([[ 1,  2,  3, 24, 25,  5, 26, 19, 27]]) tensor([28])
--------------------------------------------------
tensor([[ 42, 137, 118,   3, 247,   5, 248]]) tensor([249])
--------------------------------------------------
tensor([[ 10,  75, 111]]) tensor([112])
--------------------------------------------------
tensor([[  1,   2,   3, 141, 117,  83,   3, 277, 278]]) tensor([121])
--------------------------------------------------
tensor([[10, 29,  3, 30, 31]]) tensor([32])
--------------------------------------------------
tensor([[ 78,  79, 150, 151,  14, 152, 153]]) tensor([154])
--------------------------------------------------
tensor([[10,  2,  3, 66,  5, 67]]) tensor([68])
--------------------------------------------------
tensor([[ 1,  2,  3,  4,  5, 99]]) tensor([100])
--------------------------------------------------
tensor([[ 10, 140,   3, 141, 142,  12, 143,  83,   3, 144]]) tensor([145])
--------------------------------------------------
tensor([[ 78,  79, 288,  81,  19,  14, 289]]) tensor([85])
--------------------------------------------------
tensor([[ 42, 290, 291, 118, 292, 158, 293, 294]]) tensor([295])
--------------------------------------------------
tensor([[ 42, 137,   2, 138,  39, 175, 269]]) tensor([99])
--------------------------------------------------
tensor([[ 1,  2,  3, 33, 34,  5, 35]]) tensor([36])
--------------------------------------------------
tensor([[ 42,  18,   2,   3, 281,  12,   3, 282]]) tensor([205])
--------------------------------------------------
tensor([[  1,   2,   3,  17, 115,  83,  84]]) tensor([116])
--------------------------------------------------
tensor([[1, 2, 3, 4, 5, 6]]) tensor([7])
--------------------------------------------------
tensor([[  1,   2,   3,   4,   5, 279]]) tensor([280])
--------------------------------------------------
tensor([[ 10,  11, 189, 158, 190]]) tensor([191])
--------------------------------------------------
tensor([[ 1,  2,  3, 17, 18, 19, 20, 21, 22]]) tensor([23])
--------------------------------------------------
tensor([[42, 86, 87, 88, 89, 39, 90]]) tensor([91])
--------------------------------------------------
tensor([[  1,   2,   3, 122, 123,  19,   3,  45]]) tensor([124])
--------------------------------------------------
tensor([[  1,   2,   3, 103,   5, 104,  19, 105]]) tensor([106])
--------------------------------------------------
tensor([[10, 55,  3, 56,  5, 57]]) tensor([58])
--------------------------------------------------
tensor([[ 42,  86,  87, 241, 242,  19,  39, 243]]) tensor([244])
--------------------------------------------------
tensor([[10, 75, 76]]) tensor([77])
--------------------------------------------------
tensor([[ 42, 101,   2,   3,  17]]) tensor([102])
--------------------------------------------------
tensor([[  1,   2,   3, 146, 147,  19, 148]]) tensor([149])
--------------------------------------------------
tensor([[ 42,   2,   3, 274, 211, 275]]) tensor([276])
--------------------------------------------------
tensor([[  1,   2,   3,  92, 137,  19,   3,  45]]) tensor([185])
--------------------------------------------------
tensor([[  1,   2,   3,  69,   5, 155]]) tensor([156])
--------------------------------------------------
tensor([[ 42, 263, 264,  14, 265, 266, 158, 267]]) tensor([268])
--------------------------------------------------
tensor([[ 42, 117, 118,   3, 119,  94, 120]]) tensor([121])
--------------------------------------------------
tensor([[  1,   2,   3, 212,   5,  14, 213, 214]]) tensor([215])
--------------------------------------------------
tensor([[ 10, 140,   3, 141, 171,   5,   3,  70, 172]]) tensor([173])
--------------------------------------------------
tensor([[ 42, 167,   2,   3,  17, 168, 169]]) tensor([170])
--------------------------------------------------
tensor([[ 42, 125,   2,  62,  63,   3, 126, 127]]) tensor([128])
--------------------------------------------------
tensor([[  1,   2,   3, 234,   5, 235]]) tensor([131])
--------------------------------------------------
tensor([[  1,   2,   3,   4,   5, 113]]) tensor([114])
--------------------------------------------------
tensor([[10, 96,  3, 97]]) tensor([98])
--------------------------------------------------
tensor([[  1,   2,   3, 146,  86,  19, 192, 193]]) tensor([194])
--------------------------------------------------
tensor([[  1,   2,   3, 163, 164, 165,  83,  84]]) tensor([166])
--------------------------------------------------
tensor([[ 10,  75,   3, 296,  19, 297]]) tensor([298])
--------------------------------------------------
tensor([[ 1,  2,  3,  4,  5, 73]]) tensor([74])
--------------------------------------------------
tensor([[ 78,  79, 261, 151,  14, 262, 153]]) tensor([36])
--------------------------------------------------
tensor([[  1,   2,   3,   4,   5, 236, 237]]) tensor([238])
--------------------------------------------------
tensor([[ 1,  2,  3, 50, 51, 19,  3, 45]]) tensor([52])
--------------------------------------------------
tensor([[ 42, 174,   2,  62,  39, 175, 176,  12, 177, 178]]) tensor([179])
--------------------------------------------------
tensor([[  1,   2,   3, 221,   5, 222, 223, 224]]) tensor([225])
--------------------------------------------------
tensor([[  1,   2,   3,  33,  34,   5, 245]]) tensor([246])
--------------------------------------------------
tensor([[ 10,  11, 157, 158, 159]]) tensor([160])
--------------------------------------------------
tensor([[78, 79, 80, 81, 82, 83, 84]]) tensor([85])
--------------------------------------------------
tensor([[ 1,  2,  3, 37, 38, 39, 40]]) tensor([41])
--------------------------------------------------
tensor([[  1,   2,   3,   4,   5, 286]]) tensor([287])
--------------------------------------------------
tensor([[ 42, 255,   2, 256,  83, 257, 258]]) tensor([259])
--------------------------------------------------
tensor([[ 10, 308,   3, 309, 310]]) tensor([311])
--------------------------------------------------
tensor([[ 42,  18, 118,   3, 186, 187]]) tensor([188])
--------------------------------------------------
tensor([[ 10,  75, 208]]) tensor([209])
--------------------------------------------------
tensor([[  1,  87, 229, 230, 231, 232]]) tensor([233])
--------------------------------------------------
tensor([[ 78,  79, 195,  81,  19,   3, 196, 197, 198]]) tensor([199])
--------------------------------------------------
tensor([[ 10,   2,  62,  63,   3, 283,   5, 284]]) tensor([285])
--------------------------------------------------
tensor([[  1,   2,   3,  37, 133,   5,  26]]) tensor([134])
--------------------------------------------------
tensor([[ 1,  2,  3, 69,  5, 53]]) tensor([260])
--------------------------------------------------
tensor([[ 1,  2,  3, 69,  5,  3, 70, 71]]) tensor([72])
--------------------------------------------------
tensor([[10, 11, 12, 13, 14, 15]]) tensor([16])
--------------------------------------------------
tensor([[ 10, 140,   3, 141, 270,  93, 271,   5,   3, 272]]) tensor([273])
--------------------------------------------------
tensor([[ 1,  2,  3,  4,  5, 53]]) tensor([54])
--------------------------------------------------
tensor([[42, 18,  2, 62, 63,  3, 64, 18]]) tensor([65])
--------------------------------------------------
tensor([[ 42,   2,   3, 210, 137, 168, 211, 169]]) tensor([113])
--------------------------------------------------
tensor([[ 42, 107,   2, 108,  19, 109]]) tensor([110])
--------------------------------------------------
tensor([[ 1,  2,  3, 92, 93, 94]]) tensor([95])
--------------------------------------------------
tensor([[ 42, 312,   2, 313,  62,  63,   3, 314, 315]]) tensor([316])
--------------------------------------------------
tensor([[  1,   2,   3,   4,   5, 206]]) tensor([207])
--------------------------------------------------
tensor([[  1,   2,   3,   4,   5, 135]]) tensor([136])
--------------------------------------------------
tensor([[ 10,  29, 130, 131]]) tensor([132])
--------------------------------------------------
tensor([[ 78,  79, 129,  81,  19,   3,  21,  22]]) tensor([36])
--------------------------------------------------
tensor([[ 42, 299, 300, 118,  14, 301, 302, 158, 303, 304, 305, 306]]) tensor([307])
--------------------------------------------------
tensor([[  1,   2,   3,   4,   5, 109]]) tensor([317])
--------------------------------------------------
tensor([[42, 43, 44, 45, 46, 47, 48]]) tensor([49])
--------------------------------------------------

In [71]:
# make RNN layer
class SimpleRNN(nn.Module):

  def __init__(self, vocab_size):

    super().__init__()

    self.embedding= nn.Embedding(num_embeddings= vocab_size, embedding_dim= 50)  #return in shape(Batch_size, no. wof words, dimension of embedding)
    self.rnn= nn.RNN(50, 64, nonlinearity='relu', batch_first= True)

    self.fc= nn.Linear(64, vocab_size)


  def forward(self, question):
    embedded_words= self.embedding(question)
    hidden_state, rnn_output= self.rnn(embedded_words)   #rnn gives 2 output; hidden state value at each time sequence and final output of the rnn layer

    output= self.fc(rnn_output.squeeze(0))
    return output

In [72]:
model= SimpleRNN(len(vocab)).to(device= 'cuda')

In [73]:
criterion= nn.CrossEntropyLoss()
optimizer= optim.Adam(params= model.parameters(), lr= 0.001)

In [74]:
model.train()

SimpleRNN(
  (embedding): Embedding(324, 50)
  (rnn): RNN(50, 64, batch_first=True)
  (fc): Linear(in_features=64, out_features=324, bias=True)
)

In [75]:
for i in range(20):
  total_loss= 0
  for question, answer in dataloader:
    optimizer.zero_grad()

    question= question.to(device= 'cuda')
    answer= answer.to(device= 'cuda')



    #calculate y_pred:
    y_pred= model(question)


    loss= criterion(y_pred, answer)
    total_loss= total_loss + loss.item()

    loss.backward()

    optimizer.step()


  print(f"Epoch: {i+ 1}; loss: {total_loss/len(dataloader)}")

Epoch: 1; loss: 5.797303252749973
Epoch: 2; loss: 4.509453645017412
Epoch: 3; loss: 2.772737330198288
Epoch: 4; loss: 1.3492082662052578
Epoch: 5; loss: 0.5930416595604685
Epoch: 6; loss: 0.32647496021042266
Epoch: 7; loss: 0.20392248024129206
Epoch: 8; loss: 0.12491026495893796
Epoch: 9; loss: 0.09482251058410232
Epoch: 10; loss: 0.08092703345335192
Epoch: 11; loss: 0.04474882300969006
Epoch: 12; loss: 0.04535622232748816
Epoch: 13; loss: 0.04003797470876533
Epoch: 14; loss: 0.02742209736542362
Epoch: 15; loss: 0.012041165891827809
Epoch: 16; loss: 0.009808160858746204
Epoch: 17; loss: 0.008216726104728877
Epoch: 18; loss: 0.006883621383329026
Epoch: 19; loss: 0.0060295898350887
Epoch: 20; loss: 0.0053676432936400585

In [76]:
model.eval()

SimpleRNN(
  (embedding): Embedding(324, 50)
  (rnn): RNN(50, 64, batch_first=True)
  (fc): Linear(in_features=64, out_features=324, bias=True)
)

In [84]:
def prediction(Question: str):


  indexed_question= to_indices(Question)
  indexed_question= torch.tensor(indexed_question).unsqueeze(0).to(device= 'cuda')
  with torch.no_grad():
    y_hat= model(indexed_question)
  prob= nn.functional.softmax(y_hat, dim= 1)
  _ ,idx= torch.max(prob, dim= 1)
  if idx< 0.1:
    print("I dont know")

  else:
    keys= list(vocab.keys())
    print(keys[idx])

In [92]:
prediction("capital of france")

paris